### ISSUE TITLE
Release for scala 2.12

### ISSUE THREAD

**Issue by axos88** [greencatsoft/scalajs-angular#104]
Please do :)

**Comment by mysticfall** [comment]
Done it :)

**Comment by mysticfall** [comment]
Oh... I think I should reopen this, because I just realized I still need to add cross build settings and actually publish for Scala 2.12 as well as 2.11.

Seems I need some caffeine :)

**Comment by mysticfall** [comment]
Ok, got my coffee and just published artifacts for 2.12/2.11. Please let me know if anything does not work.

Thanks!

**Comment by axos88** [comment]
Awesome

**Comment by axos88** [comment]
,Can't see it in maven central yet, probably a caching issue?

**Comment by mysticfall** [comment]
Snapshots resides in OSS repository, i.e.:
 * https://oss.sonatype.org/content/repositories/snapshots/com/greencatsoft/scalajs-angular_sjs0.6_2.12/0.8-SNAPSHOT/scalajs-angular_sjs0.6_2.12-0.8-SNAPSHOT.jar

It will be available on Maven Central as well when we release 0.8 version later.

**Comment by axos88** [comment]
gotcha

**Comment by vasigorc** [comment]
Is 12.1 not supported and => I have to downgrade scala version?

This is the dependencies part from my build.sbt:
```
libraryDependencies ++= Seq("org.scalatest" % "scalatest_2.12" % "3.0.1" % "test",
			"org.scalacheck" %% "scalacheck" % "1.13.4" % "test",
             "org.scala-js" % "scalajs-dom_sjs0.6_2.12" % "0.9.1",
             "be.doeraene" %%% "scalajs-jquery" % "0.9.1",
             "com.greencatsoft" %%% "scalajs-angular" % "0.7")
```
and this is the output of the compile command from sbt console:
```
> compile
[info] Updating {file:/home/vgorcinschi/Documents/eclipseProjects/Algorithms/Chapter%201%20Fundamentals/algorithms1_4_34/}algorithms1_4_34...
[info] Resolving com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.7 ...
[warn] 	module not found: com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.7
[warn] ==== local: tried
[warn]   /home/vgorcinschi/.ivy2/local/com.greencatsoft/scalajs-angular_sjs0.6_2.12/0.7/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/greencatsoft/scalajs-angular_sjs0.6_2.12/0.7/scalajs-angular_sjs0.6_2.12-0.7.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/vgorcinschi/.sbt/preloaded/com.greencatsoft/scalajs-angular_sjs0.6_2.12/0.7/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/vgorcinschi/.sbt/preloaded/com/greencatsoft/scalajs-angular_sjs0.6_2.12/0.7/scalajs-angular_sjs0.6_2.12-0.7.pom
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.7: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.greencatsoft:scalajs-angular_sjs0.6_2.12:0.7 (/home/vgorcinschi/Documents/eclipseProjects/Algorithms/Chapter 1 Fundamentals/algorithms1_4_34/build.sbt#L8-13)
[warn] 		  +- default:algorithms1_4_34_sjs0.6_2.12:1.0
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.7: not found
[error] Total time: 1 s, completed 30-May-2017 8:08:09 PM
```
Please note that I also tried the 0.8-SNAPSHOT (with the resolver), but it equally fails for version incompatibility.

Thank you

**Comment by mysticfall** [comment]
@vasigorc Sorry, I happened to have totally missed your comment until today. Anyway, I just tested it on my end but couldn't reproduce the problem:
```[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/greencatsoft/scalajs-angular_sjs0.6_2.12/0.8-SNAPSHOT/scalajs-angular_sjs0.6_2.12-0.8-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.8-SNAPSHOT!scalajs-angular_sjs0.6_2.12.jar (4610ms)
```
Maybe you could delete your local cache and try it again? It seems that the cross build settings for 2.12 has been there since January, so I can't think of any reason why it doesn't work right now.

**Comment by vasigorc** [comment]
I am sorry I must be doing something wrong, but I still have the same issue (now trying to build project on a new machine):

```
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.greencatsoft:scalajs-angular_sjs0.6_2.12:0.7 (/home/vgorcinschi/workspace-scala/Algorithms/Chapter 1 Fundamentals/algorithms1_4_34/build.sbt#L8-13)
[warn] 		  +- default:algorithms1_4_34_sjs0.6_2.12:1.0
sbt.ResolveException: unresolved dependency: com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.7: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.7: not found
```

**Comment by mysticfall** [comment]
I just noticed (actually, my colleague pointed it out to me :sweat_smile:) that you are referring to the `0.7` version, which doesn't support _Scala_ `2.12` indeed.

Could you test again with `0.8-SNAPSHOT` and see if it works?

**Comment by mysticfall** [comment]
@vasigorc Urg... and I just found out that due to an error on my end, the `2.12` repository hasn't been updated for a while.

I just pushed a new version to the repository and double checked that all the artifacts are correctly published for both of the versions.

Sorry for the confusion, and please let me know if it still doesn't work.

**Comment by vasigorc** [comment]
Thank you very much @mysticfall This is now solved with your assistance:

```
> compile
[info] Updating {file:/home/vgorcinschi/workspace-scala/Algorithms/Chapter%201%20Fundamentals/algorithms1_4_34/}algorithms1_4_34...
[info] Resolving com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.8-SNAPSHOT ...
[warn] Unable to reparse com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.8-SNAPSHOT from Sonatype OSS Snapshots, using Thu Jul 06 06:50:00 CEST 2017
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/greencatsoft/scalajs-angular_sjs0.6_2.12/0.8-SNAPSHOT/scalajs-angular_sjs0.6_2.12-0.8-SNAPSHOT.jar ...
[info] 	[SUCCESSFUL ] com.greencatsoft#scalajs-angular_sjs0.6_2.12;0.8-SNAPSHOT!scalajs-angular_sjs0.6_2.12.jar (6109ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-dom_sjs0.6_2.12/0.9.2/scalajs-dom_sjs0.6_2.12-0.9.2.jar ...
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-dom_sjs0.6_2.12;0.9.2!scalajs-dom_sjs0.6_2.12.jar (1532ms)
[info] Done updating.
[success] Total time: 19 s, completed 7-Jul-2017 1:12:35 AM
```

**Comment by mysticfall** [comment]
@vasigorc Glad you have solved the problem, and thanks for letting me know!

**Comment by KarelCemus** [comment]
Hi, is there any plan to release 0.8 with Scala 2.12? Snapshot is fine but a stable release would be much better. Thanks.

**Comment by mysticfall** [comment]
@KarelCemus It's been a while since the last stable version was released, as I've been busy with my commercial project which is built on this project.

As such, the current status of the `0.9-snapshot` is pretty much stable (or stale, depending on the way you see it). But I'm aware of inconveniences involved in using snapshot dependencies in a project, so I'll probably just release `0.9` version soon.

So I'd recommend you to consider updating to the current version in the meantime.

Sorry for the inconveniences!
